changed code to remove old stuff
Utrecht-Sarbojanin/usuc-website pull request #1
Opened 2024-06-23 20:38 UTC by ArjanSaha0108

2024-06-30 11:48 UTC, aritraChatterjee commented
<img width="981" alt="image" src="https://github.com/Utrecht-Sarbojanin/usuc-website/assets/3887629/5c2c899f-09c2-432b-8358-108dd4ac2e73">
Please resolve the compilation issue

2024-06-30 11:48 UTC, aritraChatterjee requested changes

2024-06-30 11:48 UTC, aritraChatterjee commented on src/components/pages/Registration.tsx
> +/*const ticketList: Ticket[] = [
No commented code please. If you want to retain the code fragment then switch off this component using a flag.

2024-06-30 11:48 UTC, aritraChatterjee commented on src/components/pages/Registration.tsx
> +/*const Tickets = (props: any) => {
No commented code please. If you want to retain the code fragment then switch off this component using a flag.

2024-06-30 11:48 UTC, aritraChatterjee commented on tsconfig.json
> +    "jsx": "preserve"
why this change?

2024-07-14 12:55 UTC, ArjanSaha0108 reviewed
Perfect

2024-07-14 12:57 UTC, ArjanSaha0108 reviewed
Looks good

2024-07-14 12:57 UTC, ArjanSaha0108 reviewed
Looks good

2024-07-14 21:08 UTC, merged